# Generated by Django 5.0.8 on 2025-10-14 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text='Job title/position', max_length=200)),
                ('position_type', models.CharField(choices=[('leadership', 'Leadership'), ('management', 'Management'), ('staff', 'Staff')], default='staff', help_text='Category for display organization', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('photo', models.ImageField(help_text='Professional photo (recommended: 400x400px, square)', upload_to='staff/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Display order within position type')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from public display')),
                ('joined_date', models.DateField(blank=True, help_text='Date joined the assembly', null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.department')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['position_type', 'display_order', 'full_name'],
                'indexes': [models.Index(fields=['position_type'], name='staff_staff_positio_10d14b_idx'), models.Index(fields=['is_active'], name='staff_staff_is_acti_81fb95_idx')],
            },
        ),
    ]
