# Generated by Django 5.0.8 on 2025-10-19 11:52

from django.db import migrations


def create_portal_permissions(apps, schema_editor):
    """Create custom permissions for AMMA CMS Portal"""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Group = apps.get_model('auth', 'Group')

    # Get or create content type for Group model (we attach custom perms to it)
    content_type, _ = ContentType.objects.get_or_create(
        app_label='auth',
        model='group'
    )

    # Define permissions
    permissions = [
        ('can_manage_news', 'Can manage news articles'),
        ('can_manage_services', 'Can manage services'),
        ('can_manage_projects', 'Can manage projects'),
    ]

    # Create permissions
    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            content_type=content_type,
            defaults={'name': name}
        )


def remove_portal_permissions(apps, schema_editor):
    """Remove custom permissions (for migration rollback)"""
    Permission = apps.get_model('auth', 'Permission')

    # Delete the permissions
    Permission.objects.filter(
        codename__in=[
            'can_manage_news',
            'can_manage_services',
            'can_manage_projects'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_portal_permissions, remove_portal_permissions),
    ]
