# Generated by Django 5.0.8 on 2025-10-23 13:16

from django.db import migrations


def create_staff_permission(apps, schema_editor):
    """Create custom permission for staff management"""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get content type for Group model (we attach custom perms to it)
    content_type = ContentType.objects.get(
        app_label='auth',
        model='group'
    )

    # Create staff management permission
    Permission.objects.get_or_create(
        codename='can_manage_staff',
        content_type=content_type,
        defaults={'name': 'Can manage staff members'}
    )


def remove_staff_permission(apps, schema_editor):
    """Remove staff management permission (for migration rollback)"""
    Permission = apps.get_model('auth', 'Permission')

    # Delete the permission
    Permission.objects.filter(
        codename='can_manage_staff'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("staff_portal", "0002_add_documents_permission"),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_staff_permission, remove_staff_permission),
    ]
