# Generated by Django 5.0.8 on 2025-10-18 05:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#d4af37', help_text='Hex color code (e.g., #d4af37)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('excerpt', models.TextField(help_text='Brief summary (max 300 characters)', max_length=300)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('featured_image', models.ImageField(help_text='Main article image (recommended: 800x600px)', upload_to='news/%Y/%m/')),
                ('image_caption', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage and featured sections')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description (max 160 characters)', max_length=160)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='staff.staffmember')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.newscategory')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date', '-created_at'],
                'indexes': [models.Index(fields=['-published_date'], name='news_newsar_publish_efb9f8_idx'), models.Index(fields=['status'], name='news_newsar_status_f99d47_idx'), models.Index(fields=['slug'], name='news_newsar_slug_342666_idx')],
            },
        ),
    ]
