# Generated by Django 5.0.8 on 2025-10-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='file-text', help_text='Lucide icon name', max_length=50)),
                ('link_url', models.CharField(blank=True, help_text='Leave blank to use detail page, or provide external URL', max_length=200)),
                ('link_text', models.CharField(default='Learn More', max_length=50)),
                ('has_detail_page', models.BooleanField(default=True, help_text='If True, service will have a detail page with content blocks')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text Block'), ('service_grid', 'Service Box Grid'), ('list', 'List Block'), ('steps', 'Process Steps'), ('notice', 'Notice/Alert Block'), ('table', 'Table Block'), ('document', 'Document/Download Block'), ('image', 'Image Block')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title for this block', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Main content - supports markdown')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional structured data for complex blocks')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='services.service')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
