# Generated by Django 5.0.8 on 2025-10-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_detail_page',
            field=models.BooleanField(default=True, help_text='If True, service will have a detail page with content blocks'),
        ),
        migrations.AlterField(
            model_name='service',
            name='link_url',
            field=models.CharField(blank=True, help_text='Leave blank to use detail page, or provide external URL', max_length=200),
        ),
        migrations.CreateModel(
            name='ServiceContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text Block'), ('service_grid', 'Service Box Grid'), ('list', 'List Block'), ('steps', 'Process Steps'), ('notice', 'Notice/Alert Block'), ('table', 'Table Block'), ('document', 'Document/Download Block'), ('image', 'Image Block')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title for this block', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Main content - supports markdown')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional structured data for complex blocks')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='services.service')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
