# Generated by Django 5.0.8 on 2025-10-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('service', 'Service Request'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read after reviewing')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to submitter)')),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_date'],
                'indexes': [models.Index(fields=['-submitted_date'], name='contact_con_submitt_744cda_idx'), models.Index(fields=['is_read'], name='contact_con_is_read_b6d820_idx')],
            },
        ),
    ]
