# Generated by Django 5.0.8 on 2025-10-18 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Asokore Mampong Municipal Assembly', max_length=200)),
                ('description', models.TextField(default='One of 261 Metropolitan, Municipal and District Assemblies in Ghana')),
                ('location_title', models.CharField(default='Our Location', max_length=100)),
                ('location_content', models.TextField(default='The Municipality forms boundaries with Kumasi Metropolitan Assembly...')),
                ('communities_title', models.CharField(default='Communities We Serve', max_length=100)),
                ('communities_content', models.TextField(default='Our area covers Aboabo No.1, Aboabo No.2...')),
                ('structure_title', models.CharField(default='Our Structure', max_length=100)),
                ('structure_content', models.TextField(default='The Assembly comprises 15 Assembly Members...')),
                ('image', models.ImageField(blank=True, help_text='Optional image for about section', upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(max_length=500)),
                ('image', models.ImageField(help_text='Hero image (recommended: 1920x1080px)', upload_to='hero/')),
                ('button_text', models.CharField(blank=True, help_text='Leave blank to hide button', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Can be internal (/about) or external (https://...)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily hide this slide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Asokore Mampong Municipal Assembly', max_length=200)),
                ('tagline', models.CharField(default='Serving Our Community with Excellence', max_length=300)),
                ('logo', models.ImageField(help_text='Main site logo (recommended: 200x200px)', upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])])),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (recommended: 32x32px)', upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png'])])),
                ('phone', models.CharField(default='+233 024 636 1845', max_length=20)),
                ('email', models.EmailField(default='info@amma.gov.gh', max_length=254)),
                ('address', models.TextField(default='Asokore Mampong, Ashanti Region, Ghana')),
                ('office_hours', models.CharField(default='Mon - Fri: 8:00 AM - 5:00 PM', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(default='Official website of Asokore Mampong Municipal Assembly', max_length=160)),
                ('meta_keywords', models.TextField(default='AMMA, Asokore Mampong, Municipal Assembly, Ghana')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="E.g., 'Total Population'", max_length=100)),
                ('value', models.CharField(help_text="E.g., '191,402' or '15+'", max_length=50)),
                ('icon', models.CharField(default='users', help_text="Lucide icon name (without 'lucide-' prefix)", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
    ]
