# Generated by Django 5.0.8 on 2025-10-18 09:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='folder', help_text='Lucide icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('file', models.FileField(help_text='Allowed: PDF, DOC, DOCX, XLS, XLSX', upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional preview image', upload_to='documents/thumbs/')),
                ('file_size', models.CharField(blank=True, editable=False, max_length=20)),
                ('file_type', models.CharField(blank=True, editable=False, max_length=10)),
                ('document_year', models.IntegerField(blank=True, help_text='Year this document pertains to (e.g., 2024)', null=True)),
                ('document_quarter', models.CharField(blank=True, choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], help_text='Quarter this document pertains to', max_length=2, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(default=0, editable=False)),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck to hide from public')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured documents section')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_date'],
                'indexes': [models.Index(fields=['category'], name='documents_d_categor_fec314_idx'), models.Index(fields=['is_public'], name='documents_d_is_publ_2aa443_idx'), models.Index(fields=['document_year'], name='documents_d_documen_549771_idx')],
            },
        ),
    ]
