# Generated by Django 5.0.8 on 2025-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], help_text='Quarter this document pertains to', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_year',
            field=models.IntegerField(blank=True, help_text='Year this document pertains to (e.g., 2024)', null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_year'], name='documents_d_documen_549771_idx'),
        ),
    ]
